version: 2

models:
  - name: customers
    description: 1レコードが1件の顧客を示す
    columns:
      - name: customer_id
        description: 顧客IDを示す主キー
        data_tests:
          - unique
          - not_null
      - name: first_name
        description: 顧客の名
        data_tests:
          - not_null
      - name: last_name
        description: 顧客の姓
        data_tests:
          - not_null
      - name: first_order_date
        description: 初回の注文日。NULLは顧客がまだ注文したことがないことを示す
      - name: most_recent_order_date
        description: 最新の注文日。NULLは顧客がまだ注文したことがないことを示す
      - name: number_of_orders
        description: 顧客の累計注文件数。注文がない場合は0